// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyVqI2RTZRBeG9SfUMjy8lbDhyEIhEPR0',
    appId: '1:220461272066:web:6a9d75c17a00bcce9deb1b',
    messagingSenderId: '220461272066',
    projectId: 'anti-fraud-flutter',
    authDomain: 'anti-fraud-flutter.firebaseapp.com',
    databaseURL: 'https://anti-fraud-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anti-fraud-flutter.appspot.com',
    measurementId: 'G-9071YNJ6TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Ggmihbw3PNWzI8cp1pSembk-hks4OWA',
    appId: '1:220461272066:android:b1ca6d8ead62e9479deb1b',
    messagingSenderId: '220461272066',
    projectId: 'anti-fraud-flutter',
    databaseURL: 'https://anti-fraud-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anti-fraud-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovohNn7JjqNDbX4Hhz6mxSGz4cFVrWfg',
    appId: '1:220461272066:ios:ef39ab2779e3244d9deb1b',
    messagingSenderId: '220461272066',
    projectId: 'anti-fraud-flutter',
    databaseURL: 'https://anti-fraud-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anti-fraud-flutter.appspot.com',
    iosClientId: '220461272066-nq0p09tr0b8i89qi4155o1fshsupigeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.antiFraud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCovohNn7JjqNDbX4Hhz6mxSGz4cFVrWfg',
    appId: '1:220461272066:ios:ef39ab2779e3244d9deb1b',
    messagingSenderId: '220461272066',
    projectId: 'anti-fraud-flutter',
    databaseURL: 'https://anti-fraud-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anti-fraud-flutter.appspot.com',
    iosClientId: '220461272066-nq0p09tr0b8i89qi4155o1fshsupigeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.antiFraud',
  );
}
